Repository RedHatInsights/catalog-api, pull requests merged in 2018-11, with the labels that each got.

#39 Rework add_portfolio_item_to_portfolio
  config/routes.rb
  public/doc/swagger-2.yaml
Labels: bug, enhancement

#43 Add git to the DevDockerfile
  DevDockerfile
Labels: enhancement

#45 Use manageiq ruby image for the DevDockerfile
  DevDockerfile
  docker-assets/dev_entrypoint
Labels: bug

#49 Sanitize parameters before looking up a named key
  app/models/portfolio_item.rb
  spec/models/portfolio_item_spec.rb
Labels: bug

#42 Modify api versioning
  app/controllers/admins_controller.rb
  app/controllers/api.rb
  app/controllers/api/v0.rb
  app/controllers/api/v0/admins_controller.rb
  app/controllers/api/v0/base_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/api/v0x0.rb
  app/controllers/base_controller.rb
  config/routes.rb
  swagger-codegen-templates/routes.mustache
Labels: enhancement

#50 Refactor how topology grabs service_offering_ref
  app/models/order_item.rb
  app/services/service_plans.rb
  app/services/submit_order.rb
Labels: refactoring

#61 Wait for the database to be ready before trying to db:create/migrate
  docker-assets/entrypoint
Labels: unmergeable
