Repository RedHatInsights/catalog-api, pull requests merged in 2019-04, with the labels that each got.

#184 Switch ServiceOrderListener subscription strategy from messages to topics
  config/initializers/service_order_listener.rb
  lib/service_order_listener.rb
  spec/lib/service_order_listener_spec.rb
Labels: bug

#144 Add Icon PortfolioItem subresource
  Gemfile
  app/controllers/api/v1x0/icon_controller.rb
  app/services/service_offering/add_to_portfolio_item.rb
  app/services/service_offering/icons.rb
  config/routes.rb
  db/migrate/20190206213630_add_icon_column_to_portfolioitem.rb
  db/schema.rb
  public/catalog/v1.0.0/openapi.json
  spec/requests/portfolio_items_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: enhancement

#202 Remove admin, user tagged tests
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
Labels: enhancement

#203 Update insights proxy URL from "insights/platform" to 'hybrid"
  README.md
Labels: bug

#129 Rbac list items
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/application_controller.rb
  lib/exceptions.rb
  lib/rbac/access.rb
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/lib/rbac/access_spec.rb
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_rbac_spec.rb
  spec/requests/portfolios_spec.rb
  spec/requests/progress_message_spec.rb
  spec/support/requests_spec_helper.rb
Labels: enhancement

#206 Move order_item context setting to only save if new_record
  app/models/order_item.rb
  spec/services/catalog/order_item_transition_spec.rb
Labels: bug

#208 Unify spandx files into a single config file.
  README.md
  config/spandx.config.js
  config/spandx/linux.js
Labels: refactoring

#211 Removed bypassing tenancy code
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
  spec/support/service_spec_helper.rb
Labels: refactoring, testing

#210 Support for Catalog Admin to access all objects
  lib/rbac/access.rb
  spec/lib/rbac/access_spec.rb
Labels: enhancement

#219 Added missing tests
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
Labels: testing

#218 Added x-rh-insights-request-id and original_url to headers
  spec/support/service_spec_helper.rb
Labels: testing

#216 Removed some more bypass tenancy calls
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/models/tenant_spec.rb
Labels: refactoring, testing

#225 Expose 'external_url' property to the API for OrderItems
  app/models/order_item.rb
  public/catalog/v1.0.0/openapi.json
Labels: enhancement

#226 Change OrderID to string in ApprovalRequest content object
  app/services/catalog/create_approval_request.rb
  spec/services/catalog/create_approval_request_spec.rb
Labels: bug

#228 Spec cleanup
  spec/lib/approval_request_listener_spec.rb
  spec/services/catalog/add_to_order_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/support/service_spec_helper.rb
Labels: refactoring, testing

#234 Handle IdentityError
  app/controllers/application_controller.rb
Labels: testing

#229 Fixed logic and spec coverage
  app/services/service_offering/add_to_portfolio_item.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: refactoring, testing

#232 Added missing specs
  spec/lib/dev_credentials_spec.rb
Labels: testing

#243 RE Re enable RBAC
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/api/v1x0/mixins/rbac_mixin.rb
  spec/requests/portfolios_rbac_spec.rb
  spec/requests/portfolios_rbac_write_access_spec.rb
Labels: enhancement

#246 The id_list is a collection of string ids
  spec/lib/rbac/access_spec.rb
  spec/requests/portfolios_rbac_spec.rb
Labels: testing

#251 Simple rake task to display details about an order or orders.
  README.md
  lib/tasks/.keep
  lib/tasks/orders.rake
Labels: enhancement

#255 Update swagger references to OpenAPI and remove unneeded artifacts.
  Gemfile
  README.md
  config/initializers/swagger_ui_engine.rb
  spec/swagger_spec.rb
Labels: refactoring

#249 Add filtering from common gem
  app/controllers/api/v1x0/mixins/index_mixin.rb
  lib/api/docs.rb
  spec/requests/portfolios_rbac_spec.rb
  spec/requests/portfolios_spec.rb
Labels: enhancement

#257 Expose owner from the order model
  app/models/order.rb
Labels: enhancement

#258 Set owner to readOnly in the api docs
  public/catalog/v1.0.0/openapi.json
Labels: bug

#261 Use default owners in factories
  spec/factories/order.rb
  spec/factories/order_item.rb
  spec/factories/portfolio_items.rb
  spec/factories/portfolios.rb
Labels: refactoring, testing

#269 Remove potential duplication from sequence
  spec/factories/tenants.rb
Labels: bug

#276 Change filter "operator" to proper accessor name "operation"
  lib/rbac/access.rb
  lib/rbac/acls.rb
  spec/lib/rbac/access_spec.rb
  spec/support/rbac_shared_contexts.rb
Labels: bug

#280 Use instance_double for RBAC test objects
  spec/lib/rbac/access_spec.rb
  spec/lib/rbac/query_shared_resource_spec.rb
  spec/support/rbac_shared_contexts.rb
Labels: testing
