Repository RedHatInsights/catalog-api, pull requests merged in 2019-03, with the labels that each got.

#121 Add support for soft-deletion of portfolios
  app/controllers/api/v0/admins_controller.rb
  app/controllers/api/v0/base_controller.rb
  app/controllers/api/v0x1/portfolios_controller.rb
  app/models/portfolio.rb
  db/migrate/20190219204110_add_discarded_at_to_portfolios.rb
  db/schema.rb
  public/service_portal/v0.1.0/openapi.json
  spec/requests/portfolios_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
Labels: enhancement

#127 Add PATCH support for Portfolio Items
  app/controllers/api/v0x1/portfolio_items_controller.rb
  config/routes.rb
  public/service_portal/v0.1.0/openapi.json
  spec/requests/portfolio_items_spec.rb
Labels: enhancement

#126 Integrate with RBAC Service
  Gemfile
  lib/exceptions.rb
  lib/rbac/access.rb
  lib/rbac/service.rb
  spec/lib/rbac/access_spec.rb
  spec/lib/rbac/service_spec.rb
Labels: enhancement

#96 Add basic auth support for Topology API calls
  README.md
  lib/topological_inventory.rb
Labels: enhancement

#135 Replace Headers with Request
  app/controllers/application_controller.rb
  app/controllers/concerns/response.rb
  lib/exceptions.rb
  spec/controllers/api/v0x0/application_controller_spec.rb
  spec/factories/tenants.rb
  spec/spec_helper.rb
  spec/support/service_spec_helper.rb
Labels: bug

#128 Running portal locally but access Insights UI on dev cluster
  README.md
  config/spandx/service-portal_linux.js
  config/spandx/service-portal_mac.js
Labels: enhancement

#133 Forward Headers to topology service
  lib/topological_inventory.rb
  spec/lib/topological_inventory_spec.rb
Labels: enhancement

#145 The options need to be symbols not strings
  lib/rbac/service.rb
  spec/lib/rbac/service_spec.rb
Labels: bug

#142 Add 'context' column to OrderItem
  app/models/order_item.rb
  db/migrate/20190307171244_add_context_to_order_item.rb
  db/schema.rb
  spec/services/catalog/add_to_order_spec.rb
Labels: enhancement

#146 Add workflow_ref to Portfolio CRUD
  app/controllers/api/v0x1/portfolios_controller.rb
  db/migrate/20190311212914_add_workflow_ref.rb
  db/schema.rb
  public/catalog/v0.1.0/openapi.json
  spec/factories/portfolios.rb
  spec/models/portfolio_spec.rb
  spec/requests/portfolios_spec.rb
Labels: enhancement

#150 rescue on NoKeyError when attempting to set ManageIQ::API::Common::Request.current
  app/controllers/application_controller.rb
Labels: bug

#148 Add workflow_ref to PortfolioItem CRUD
  app/controllers/api/v0x1/portfolio_items_controller.rb
  db/migrate/20190312200721_add_workflow_ref_to_portfolio_item.rb
  db/schema.rb
  public/catalog/v0.1.0/openapi.json
  spec/requests/portfolio_items_spec.rb
Labels: enhancement

#141 Add "owner" column to models that have tenancy
  app/models/concerns/owner_field.rb
  app/models/order.rb
  app/models/order_item.rb
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  db/migrate/20190305144853_add_owners_column_to_tenancy_tables.rb
  db/schema.rb
  public/catalog/v0.1.0/openapi.json
  spec/controllers/api/v0x0/application_controller_spec.rb
  spec/factories/order.rb
  spec/factories/order_item.rb
  spec/factories/portfolio_items.rb
  spec/factories/portfolios.rb
  spec/lib/service_order_listener_spec.rb
  spec/models/portfolio_item_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/services/catalog/add_to_order_spec.rb
Labels: enhancement

#152 Modify as_json serializer to handle time and id strings.
  config/initializers/application_record_serializing.rb
  lib/open_api/serializer.rb
  spec/controllers/api/v0x0/application_controller_spec.rb
  spec/lib/open_api/serializer_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
Labels: enhancement

#159 Point major version endpoint to newest minor version
  config/routes.rb
  spec/controllers/api/v0x0/application_controller_spec.rb
Labels: enhancement

#153 Create a lookup for workflow IDs for OrderItem.
  app/models/portfolio_item.rb
  spec/models/portfolio_item_spec.rb
Labels: enhancement

#158 Update in-model as_json methods to use updated OpenApi method.
  app/models/order.rb
  app/models/order_item.rb
  app/models/progress_message.rb
Labels: refactoring

#149 Share/Unshare/Query Resource
  lib/rbac/acls.rb
  lib/rbac/query_shared_resource.rb
  lib/rbac/roles.rb
  lib/rbac/share_resource.rb
  lib/rbac/unshare_resource.rb
  lib/rbac/utilities.rb
  spec/lib/rbac/query_shared_resource_spec.rb
  spec/lib/rbac/share_resource_spec.rb
  spec/lib/rbac/unshare_resource_spec.rb
  spec/support/rbac_shared_contexts.rb
Labels: enhancement

#165 Set base_path as part of client configuration
  lib/topological_inventory.rb
Labels: bug

#157 Share Unshare Query OpenAPI for Portfolios
  app/controllers/api/v0x1/portfolios_controller.rb
  config/routes.rb
  public/catalog/v0.1.0/openapi.json
  spec/requests/portfolios_spec.rb
Labels: enhancement

#170 Change Approval State Column to Int
  db/migrate/20190322202902_change_approval_state_column_type.rb
  db/schema.rb
Labels: bug

#160 Replace before block with around for disabling tenancy
  spec/controllers/api/v0x0/application_controller_spec.rb
  spec/models/portfolio_spec.rb
  spec/models/tenant_spec.rb
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/requests/progress_message_spec.rb
  spec/support/requests_spec_helper.rb
Labels: bug, refactoring

#168 Add approval service listener
  app/models/order_item.rb
  bin/approval_request_listener
  config/initializers/approval_request_listener.rb
  db/migrate/20190322191656_add_approval_request_reason.rb
  db/schema.rb
  lib/approval_request_listener.rb
  spec/lib/approval_request_listener_spec.rb
Labels: enhancement

#179 Change to v1 api
  app/controllers/api/v0/admins_controller.rb
  app/controllers/api/v0/base_controller.rb
  app/controllers/api/v0/users_controller.rb
  app/controllers/api/v0x0.rb
  app/controllers/api/v0x1.rb
  app/controllers/api/v1x0.rb
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/api/v1x0/mixins/show_mixin.rb
  app/controllers/api/v1x0/order_items_controller.rb
  app/controllers/api/v1x0/orders_controller.rb
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/progress_messages_controller.rb
  app/controllers/api/v1x0/provider_control_parameters_controller.rb
  app/controllers/api/v1x0/service_plans_controller.rb
  config/routes.rb
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/requests/progress_message_spec.rb
  spec/support/requests_spec_helper.rb
  spec/swagger_spec.rb
Labels: enhancement

#177 Added route to fetch openapi.json
  app/controllers/api/v1x0.rb
  config/routes.rb
  spec/requests/root_spec.rb
Labels: enhancement

#183 Allow only v1.0.0 for openapi.json
  app/controllers/api/v1x0.rb
  public/catalog/v0.0.1/openapi.json
  public/catalog/v1.0.0/openapi.json
Labels: bug

#185 Add v1.0 to the openapi.json servers list
  public/catalog/v1.0.0/openapi.json
Labels: bug, enhancement

#176 Sync order_item and progress message update times
  app/models/order_item.rb
  spec/models/order_item_spec.rb
Labels: refactoring

#178 Send Provision Request when Approval is Complete
  app/services/catalog/order_item_transition.rb
  app/services/catalog/submit_order.rb
  lib/approval_request_listener.rb
  spec/lib/approval_request_listener_spec.rb
  spec/services/catalog/order_item_transition_spec.rb
  spec/services/catalog/submit_order_spec.rb
Labels: enhancement
