Repository RedHatInsights/catalog-api, pull requests merged in 2019-09, with the labels that each got.

#376 Sprint 36 merge to stable
  Dockerfile
  Gemfile
  app/controllers/api/v1x0/icons_controller.rb
  app/controllers/api/v1x0/mixins/rbac_mixin.rb
  app/controllers/api/v1x0/mixins/validation_mixin.rb
  app/controllers/api/v1x0/order_items_controller.rb
  app/controllers/api/v1x0/orders_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/settings_controller.rb
  app/models/icon.rb
  app/models/image.rb
  app/models/order.rb
  app/models/order_item.rb
  app/models/progress_message.rb
  app/services/catalog/cancel_order.rb
  app/services/catalog/create_approval_request.rb
  app/services/catalog/create_icon.rb
  app/services/catalog/duplicate_image.rb
  app/services/catalog/submit_order.rb
  app/services/catalog/update_icon.rb
  app/services/service_offering/add_to_portfolio_item.rb
  config/routes.rb
  db/migrate/20190805140757_create_image_table.rb
  db/migrate/20190807153836_add_discarded_at_to_order_items.rb
  db/migrate/20190807153851_add_discarded_at_to_progress_messages.rb
  db/migrate/20190808161627_add_discarded_at_to_orders.rb
  db/migrate/20190821224909_rename_ordered_at_columns.rb
  db/schema.rb
  lib/rbac/access.rb
  lib/rbac/roles.rb
  public/doc/openapi-3-v1.0.0.json
  spec/factories/icon.rb
  spec/lib/rbac/roles_spec.rb
  spec/models/order_item_spec.rb
  spec/models/order_spec.rb
  spec/requests/icons_spec.rb
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolios_spec.rb
  spec/requests/progress_message_spec.rb
  spec/requests/settings_spec.rb
  spec/services/catalog/cancel_order_spec.rb
  spec/services/catalog/create_icon_spec.rb
  spec/services/catalog/duplicate_image_spec.rb
  spec/services/catalog/update_icon_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/images/miq_logo.jpg
  spec/support/images/miq_logo.png
  spec/support/images/miq_logo.svg
  spec/support/images/ocp_logo.jpg
  spec/support/images/ocp_logo.png
  spec/support/images/ocp_logo.svg
  spec/support/images/ocp_logo_dupe.jpg
  spec/support/images/ocp_logo_dupe.png
  spec/support/images/ocp_logo_dupe.svg
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: stable

#377 Sprint 36 Hotfix#1 merge to stable
  app/models/image.rb
  db/migrate/20190805140757_create_image_table.rb
  spec/support/images/topology_image.svg
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: stable

#383 validate name, display_name
  app/models/portfolio_item.rb
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement

#384 Change external_tenant to string
  app/controllers/application_controller.rb
  db/migrate/20190910203425_change_external_tenant_to_string.rb
  db/schema.rb
Labels: enhancement

#372 Validate Product with Sources API
  Gemfile
  app/services/catalog/submit_order.rb
  app/services/catalog/validate_source.rb
  app/services/concerns/source_mixin.rb
  app/services/service_offering/add_to_portfolio_item.rb
  lib/exceptions.rb
  lib/sources.rb
  spec/lib/sources_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/validate_source_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
Labels: enhancement

#379 Use order_service_offering instead of deprecated order_service_plan
  app/services/catalog/submit_order.rb
  spec/services/catalog/submit_order_spec.rb
Labels: unmergeable

#387 Added enum for permissions and minItems for groups
  public/doc/openapi-3-v1.0.0.json
Labels: enhancement
