Repository RedHatInsights/catalog-api, pull requests merged in 2019-10, with the labels that each got.

#409 Allow for nulled attributes for workflow_ref
  public/doc/openapi-3-v1.0.0.json
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
Labels: bug

#407 Sprint 38 merge to stable
  README.md
  app/controllers/api/graphql_controller.rb
  app/controllers/api/v1/graphql_controller.rb
  app/controllers/api/v1x0.rb
  app/controllers/api/v1x0/icons_controller.rb
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/api/v1x0/mixins/rbac_mixin.rb
  app/controllers/api/v1x0/order_items_controller.rb
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/settings_controller.rb
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/controllers/internal/v0/notify_controller.rb
  app/models/order_item.rb
  app/models/portfolio_item.rb
  app/services/catalog/add_to_order.rb
  app/services/catalog/create_icon.rb
  app/services/catalog/order_item_sanitized_parameters.rb
  app/services/catalog/provider_control_parameters.rb
  app/services/catalog/service_plans.rb
  app/services/service_offering/add_to_portfolio_item.rb
  lib/approval.rb
  lib/catalog/json_schema_reader.rb
  lib/rbac/access.rb
  lib/rbac/acls.rb
  lib/rbac/roles.rb
  lib/rbac/seed.rb
  lib/rbac/service.rb
  lib/rbac/share_resource.rb
  public/doc/openapi-3-v1.0.0.json
  schemas/json/no_service_plan.erb
  schemas/json/openshift_control_parameters.erb
  schemas/json/service_plan.erb
  spec/lib/dev_credentials_spec.rb
  spec/lib/rbac/query_shared_resource_spec.rb
  spec/lib/rbac/service_spec.rb
  spec/lib/rbac/share_resource_spec.rb
  spec/lib/rbac/unshare_resource_spec.rb
  spec/models/portfolio_item_spec.rb
  spec/requests/icons_spec.rb
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_rbac_spec.rb
  spec/requests/portfolios_spec.rb
  spec/services/catalog/add_to_order_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
  spec/services/catalog/create_icon_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/provider_control_parameters_spec.rb
  spec/services/catalog/service_plans_spec.rb
  spec/services/catalog/validate_source_spec.rb
  spec/support/service_spec_helper.rb
Labels: stable

#418 Added request_completed_at to ApprovalRequest
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#391 Create seeding mechanism
  app/controllers/api/v1/tenants_controller.rb
  app/controllers/api/v1x0.rb
  app/models/rbac_seed.rb
  app/services/group/seed.rb
  config/routes.rb
  db/migrate/20190912201728_add_rbac_seed.rb
  db/schema.rb
  lib/rbac/seed.rb
  public/doc/openapi-3-v1.0.0.json
  spec/open_api_spec.rb
  spec/requests/tenant_spec.rb
  spec/support/service_spec_helper.rb
Labels: enhancement

#427 Add Tenant scope to filter lookups within context of the current tenant
  app/controllers/api/v1/tenants_controller.rb
  app/models/tenant.rb
  spec/models/tenant_spec.rb
Labels: bug

#429 Remove display_name validation
  app/models/portfolio_item.rb
Labels: enhancement, refactoring

#430 Sprint 39 merge to stable
  Gemfile
  README.md
  app/controllers/api.rb
  app/controllers/api/v1.rb
  app/controllers/api/v1/approval_requests_controller.rb
  app/controllers/api/v1/graphql_controller.rb
  app/controllers/api/v1/icons_controller.rb
  app/controllers/api/v1/mixins/index_mixin.rb
  app/controllers/api/v1/mixins/rbac_mixin.rb
  app/controllers/api/v1/mixins/show_mixin.rb
  app/controllers/api/v1/mixins/validation_mixin.rb
  app/controllers/api/v1/order_items_controller.rb
  app/controllers/api/v1/orders_controller.rb
  app/controllers/api/v1/portfolio_items_controller.rb
  app/controllers/api/v1/portfolios_controller.rb
  app/controllers/api/v1/progress_messages_controller.rb
  app/controllers/api/v1/provider_control_parameters_controller.rb
  app/controllers/api/v1/service_plans_controller.rb
  app/controllers/api/v1/settings_controller.rb
  app/controllers/api/v1/tenants_controller.rb
  app/controllers/api/v1x0.rb
  app/controllers/application_controller.rb
  app/models/portfolio_item.rb
  app/models/rbac_seed.rb
  app/models/tenant.rb
  app/services/catalog/cancel_order.rb
  app/services/catalog/create_approval_request.rb
  app/services/catalog/notify_approval_request.rb
  app/services/group/seed.rb
  config/initializers/load_extensions.rb
  config/routes.rb
  db/migrate/20190912201728_add_rbac_seed.rb
  db/migrate/20191002180129_add_request_completed_at_to_approval_requests.rb
  db/schema.rb
  lib/approval.rb
  lib/approval/service.rb
  lib/rbac/seed.rb
  lib/tasks/migrate_icons.rake
  public/doc/openapi-3-v1.0.0.json
  schemas/json/no_service_plan.erb
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/lib/approval/service_spec.rb
  spec/models/tenant_spec.rb
  spec/open_api_spec.rb
  spec/requests/icons_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_rbac_read_access_spec.rb
  spec/requests/portfolios_rbac_spec.rb
  spec/requests/portfolios_spec.rb
  spec/requests/tenant_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
  spec/services/catalog/notify_approval_request_spec.rb
  spec/services/catalog/service_plans_spec.rb
  spec/support/service_spec_helper.rb
Labels: stable

#438 Remove readOnly requirements for product attributes
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#449 Fix duplicate image spec failing on specific order
  spec/services/catalog/duplicate_image_spec.rb
Labels: bug

#447 Fix tag unique index and implement tagging unique fix from topo
  app/models/concerns/acts_as_taggable_on.rb
  db/migrate/20191024175018_change_index_on_tags.rb
  db/schema.rb
  spec/requests/tags_spec.rb
Labels: bug

#450 The tenant_seed method doesn't need pagination parameters
  public/doc/openapi-3-v1.0.0.json
Labels: invalid

#448 Expose an OrderItem object for add to order
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#441 Add nullable true to all nullable PortfolioItem attributes
  public/doc/openapi-3-v1.0.0.json
  spec/open_api_spec.rb
  spec/requests/portfolio_items_spec.rb
Labels: bug
