Repository RedHatInsights/catalog-api, pull requests merged in 2019-11, with the labels that each got.

#463 Removed workflow_ref from catalog
  app/controllers/api/v1/portfolios_controller.rb
  app/models/approval_request.rb
  app/models/portfolio_item.rb
  app/services/catalog/create_approval_request.rb
  db/migrate/20191101193710_remove_workflow_ref_from_portfolio_item.rb
  db/schema.rb
  public/doc/openapi-3-v1.0.0.json
  spec/factories/approval_requests.rb
  spec/models/portfolio_item_spec.rb
  spec/models/portfolio_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/services/catalog/approval_transition_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
Labels: refactoring

#469 [Stable] Changed reference to RBAC::Service to come from common gem
  lib/tasks/porfolios.rake
Labels: stable

#470 Expose internal tenant id
  public/doc/openapi-3-v1.0.0.json
  spec/requests/tenant_spec.rb
Labels: enhancement

#476 [Stable] Updated to manageiq-api-common prior to "Insights" rename.
  Gemfile
  Jenkinsfile-smoke.groovy
Labels: stable

#464 Change `Icon` relation to use `has_one` instead of `has_many`
  app/controllers/api/v1/icons_controller.rb
  app/models/icon.rb
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  app/services/catalog/create_icon.rb
  app/services/service_offering/add_to_portfolio_item.rb
  app/services/service_offering/icons.rb
  db/migrate/20191104171526_add_icon_id_to_portfolio_and_portfolio_item.rb
  db/schema.rb
  public/doc/openapi-3-v1.0.0.json
  spec/factories/icon.rb
  spec/requests/icons_spec.rb
  spec/services/catalog/create_icon_spec.rb
  spec/services/catalog/update_icon_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
Labels: refactoring

#483 Fix service_plan return to return the proper `create_json_schema` payload
  app/controllers/api/v1/service_plans_controller.rb
  app/services/catalog/service_plan_json.rb
  public/doc/openapi-3-v1.0.0.json
  schemas/json/no_service_plan.erb
  schemas/json/service_plan.erb
  spec/requests/service_plans_spec.rb
  spec/services/catalog/service_plan_json_spec.rb
Labels: bug, enhancement

#488 Fix wrong description and summary
  public/doc/openapi-3-v1.0.0.json
Labels: bug

#490 Sprint 42 Hotfix #2 merge to stable
  app/controllers/api/v1/service_plans_controller.rb
  app/services/catalog/service_plan_json.rb
  public/doc/openapi-3-v1.0.0.json
  schemas/json/no_service_plan.erb
  schemas/json/service_plan.erb
  spec/requests/service_plans_spec.rb
  spec/services/catalog/service_plan_json_spec.rb
Labels: stable
