Repository RedHatInsights/catalog-api, pull requests merged in 2019-01, with the labels that each got.

#80 Update ruby gems for travis
  .travis.yml
Labels: enhancement

#79 Remove habtm relationship on portfolios
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  db/migrate/20190102182940_remove_join_table.rb
  db/schema.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
Labels: enhancement

#81 Removed order_items from order object
  db/migrate/20190104200809_remove_order_items_from_order.rb
  public/doc/swagger-2.yaml
Labels: bug

#84 Add delete endpoint for portfolio_item
  app/controllers/api/v0/admins_controller.rb
  config/routes.rb
  public/doc/swagger-2.yaml
  spec/requests/portfolio_items_spec.rb
Labels: enhancement

#87 Missed attaching the db/schema changes
  db/schema.rb
Labels: enhancement

#86 Use manageiq-loggers for rails logging
  Gemfile
  config/application.rb
Labels: enhancement

#89 Add some basic prometheus metrics at the /metrics endpoint
  Gemfile
  config/application.rb
Labels: enhancement

#88 Add a new column to PortfolioItem to store service_offering_source_ref
  app/services/service_catalog/service_offering.rb
  db/migrate/20190116194409_add_service_offering_source_ref_to_portfolio_items.rb
  db/schema.rb
  spec/requests/portfolio_items_spec.rb
  spec/services/service_catalog/service_offering_spec.rb
Labels: enhancement

#91 Add metrics and logging from manageiq-api-common
  Gemfile
  app/models/order_item.rb
  config/application.rb
Labels: enhancement

#92 Removing DevDockerfile since it is no longer needed
  DevDockerfile
Labels: enhancement

#90 Added support for Provider Control Parameters
  app/controllers/api/v0/base_controller.rb
  app/services/service_catalog/provider_control_parameters.rb
  config/routes.rb
  public/doc/swagger-2.yaml
  schemas/json/openshift_control_parameters.json
  spec/factories/portfolio_items.rb
  spec/requests/portfolio_items_spec.rb
  spec/services/service_catalog/provider_control_parameters_spec.rb
Labels: enhancement

#94 Fix PortfolioItem belongs_to :portfolio statement
  app/models/portfolio_item.rb
Labels: refactoring

#102 Add a Test for adding portfolio items to portfolios
  spec/requests/portfolios_spec.rb
Labels: testing
