Repository RedHatInsights/catalog-api, pull requests merged in 2019-07, with the labels that each got.

#319 Bug fix for invalid values in permissions
  app/controllers/api/v1x0/portfolios_controller.rb
  app/services/catalog/portfolio_permission.rb
  public/doc/openapi-3-v1.0.0.json
  spec/requests/portfolios_spec.rb
Labels: bug

#303 Cancel a running order
  app/controllers/api/v1x0/orders_controller.rb
  app/models/approval_request.rb
  app/services/catalog/approval_transition.rb
  app/services/catalog/cancel_order.rb
  app/services/catalog/order_state_transition.rb
  config/application.rb
  config/routes.rb
  lib/approval.rb
  lib/exceptions.rb
  public/doc/openapi-3-v1.0.0.json
  spec/requests/orders_spec.rb
  spec/services/catalog/approval_transition_spec.rb
  spec/services/catalog/cancel_order_spec.rb
  spec/services/catalog/order_state_transition_spec.rb
Labels: enhancement

#329 Portfolio share/unshare return 422 if group is not valid
  lib/rbac/utilities.rb
  public/doc/openapi-3-v1.0.0.json
  spec/lib/rbac/share_resource_spec.rb
  spec/lib/rbac/unshare_resource_spec.rb
Labels: bug

#330 Sprint 32 merge to stable
  .codeclimate.yml
  .rubocop_catalog.yml
  app/controllers/api/v1x0/orders_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/models/approval_request.rb
  app/services/catalog/approval_transition.rb
  app/services/catalog/cancel_order.rb
  app/services/catalog/copy_portfolio_item.rb
  app/services/catalog/order_state_transition.rb
  app/services/catalog/portfolio_permission.rb
  config/application.rb
  config/routes.rb
  lib/approval.rb
  lib/exceptions.rb
  lib/rbac/utilities.rb
  public/doc/openapi-3-v1.0.0.json
  spec/lib/rbac/share_resource_spec.rb
  spec/lib/rbac/unshare_resource_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/services/catalog/approval_transition_spec.rb
  spec/services/catalog/cancel_order_spec.rb
  spec/services/catalog/copy_portfolio_item_spec.rb
  spec/services/catalog/copy_portfolio_spec.rb
  spec/services/catalog/order_state_transition_spec.rb
Labels: stable

#326 Split internal notify endpoint into two endpoints
  app/controllers/internal/v0/notify_controller.rb
  app/services/catalog/notify.rb
  app/services/catalog/notify_approval_request.rb
  config/application.rb
  config/routes.rb
  lib/exceptions.rb
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/open_api_spec.rb
  spec/services/catalog/notify_approval_request_spec.rb
  spec/services/catalog/notify_spec.rb
Labels: enhancement

#339 Update migrate_icons rake task to copy tenant_id so migration runs smoothly
  lib/tasks/migrate_icons.rake
Labels: bug

#342 Sprint 33 merge to stable
  Jenkinsfile-smoke.groovy
  app/controllers/api/v1x0/icons_controller.rb
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/internal/v0/notify_controller.rb
  app/models/icon.rb
  app/models/portfolio_item.rb
  app/services/catalog/notify.rb
  app/services/catalog/notify_approval_request.rb
  app/services/service_offering/add_to_portfolio_item.rb
  config/application.rb
  config/routes.rb
  db/migrate/20190625173111_create_icons.rb
  db/schema.rb
  lib/exceptions.rb
  lib/tasks/migrate_icons.rake
  public/doc/openapi-3-v1.0.0.json
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/factories/icon.rb
  spec/open_api_spec.rb
  spec/requests/icons_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/services/catalog/notify_approval_request_spec.rb
  spec/services/catalog/notify_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/service_offering_topological_service_offering_helper.rb
  spec/support/service_spec_helper.rb
Labels: stable

#346 update OrderItemSanitizedParameters to handle ansible service plans
  app/services/catalog/order_item_sanitized_parameters.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
Labels: enhancement

#349 Only set long_description when provided as part of the source_offering
  app/services/service_offering/add_to_portfolio_item.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
Labels: bug

#348 Remove OpenShift sanitization code and clean up SanitizedParameters spec
  app/services/catalog/order_item_sanitized_parameters.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
Labels: enhancement
