Repository RedHatInsights/catalog-api, pull requests merged in 2019-02, with the labels that each got.

#98 Moved a service object to the correct location
  app/controllers/api/v0/admins_controller.rb
  app/services/add_to_order.rb
  app/services/service_catalog/add_to_order.rb
  spec/requests/orders_spec.rb
  spec/services/add_to_order_spec.rb
  spec/services/service_catalog/add_to_order_spec.rb
Labels: refactoring

#101 Add Tenancy to controllers
  Gemfile
  app/controllers/application_controller.rb
  app/models/tenant.rb
  config/initializers/load_extensions.rb
  db/migrate/20190131192312_modify_tenant_table.rb
  db/schema.rb
  spec/controllers/api/v0x0/application_controller_spec.rb
  spec/factories/portfolio_items.rb
  spec/factories/portfolios.rb
  spec/factories/tenants.rb
  spec/models/portfolio_spec.rb
Labels: enhancement

#104 Switched access to collection.data instead of array
  app/services/service_catalog/provider_control_parameters.rb
  app/services/service_catalog/service_plans.rb
  spec/services/service_catalog/provider_control_parameters_spec.rb
  spec/services/service_catalog/service_plans_spec.rb
Labels: bug

#103 Added pagination support
  app/controllers/api/v0/admins_controller.rb
  app/controllers/api/v0/base_controller.rb
  app/controllers/api/v0x1.rb
  app/controllers/api/v0x1/mixins/index_mixin.rb
  app/models/order.rb
  app/models/order_item.rb
  app/models/progress_message.rb
  config/routes.rb
  public/doc/swagger-2-v0.0.1.yaml
  public/doc/swagger-2-v0.1.0.yaml
  spec/factories/order_item.rb
  spec/factories/progress_messages.rb
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
  spec/requests/progress_message_spec.rb
Labels: enhancement

#105 Fixed swagger ui engine
  config/initializers/swagger_ui_engine.rb
Labels: enhancement

#109 Allow for v0 redirects on api requests
  config/initializers/action_dispatch-routing-option_redirect.rb
  config/routes.rb
  spec/controllers/api/v0x0/application_controller_spec.rb
  spec/support/requests_spec_helper.rb
Labels: bug, enhancement

#97 Refactor ServiceOffering to a different namespace
  app/controllers/api/v0/admins_controller.rb
  app/models/portfolio_item.rb
  app/services/service_offering/add_to_portfolio_item.rb
  spec/models/portfolio_item_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: enhancement

#117 Correct "Openshift" to "OpenShift"
  schemas/json/openshift_control_parameters.json
Labels: bug

#114 Updated docs for DELETE /portfolio with proper response
  public/service_portal/v0.1.0/openapi.json
Labels: bug

#118 Modify what column source_id is mapped to
  app/services/service_offering/add_to_portfolio_item.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: bug, refactoring

#122 Change to list container_projects directly on a source
  app/services/service_catalog/provider_control_parameters.rb
  spec/services/service_catalog/provider_control_parameters_spec.rb
Labels: bug

#123 Create resource based routes
  app/controllers/api/v0/base_controller.rb
  app/controllers/api/v0x1/mixins/index_mixin.rb
  app/controllers/api/v0x1/order_items_controller.rb
  app/controllers/api/v0x1/orders_controller.rb
  app/controllers/api/v0x1/portfolio_items_controller.rb
  app/controllers/api/v0x1/portfolios_controller.rb
  app/controllers/api/v0x1/progress_messages_controller.rb
  app/controllers/api/v0x1/provider_control_parameters_controller.rb
  app/controllers/api/v0x1/service_plans_controller.rb
  app/controllers/application_controller.rb
  config/routes.rb
  public/service_portal/v0.1.0/openapi.json
  spec/requests/order_items_spec.rb
  spec/requests/orders_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/portfolios_spec.rb
Labels: enhancement, refactoring

#124 Resolved openapi generator errors for v0.1.0 spec
  public/service_portal/v0.1.0/openapi.json
Labels: bug

#119 Add docs for new Portfolio Item fields
  db/migrate/20190218162940_rename_provider_display_name.rb
  db/schema.rb
  public/service_portal/v0.1.0/openapi.json
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/support/service_offering_topological_service_offering_helper.rb
Labels: bug

#120 Add support for soft-deletion of portfolio_items
  Gemfile
  app/controllers/api/v0/admins_controller.rb
  app/controllers/api/v0x1/portfolio_items_controller.rb
  app/models/portfolio_item.rb
  db/migrate/20181017200423_add_service_offering_ref_to_portfolio_item.rb
  db/migrate/20190219143359_add_discarded_at_to_portfolio_items.rb
  db/schema.rb
  spec/requests/portfolio_items_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
Labels: enhancement
