Repository RedHatInsights/catalog-api, pull requests merged in 2020-10, with the labels that each got.

#825 Sprint 62 merge master to stable
  Dockerfile
  Gemfile
  app/controllers/api/v1x0/tags_controller.rb
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/tags_controller.rb
  app/models/order.rb
  app/models/order_item.rb
  app/services/api/v1x0/catalog/copy_portfolio.rb
  app/services/api/v1x0/catalog/copy_portfolio_item.rb
  app/services/api/v1x2/catalog/evaluate_order_process.rb
  docker-assets/librdkafka-1.5.0.tar.gz
  lib/catalog/approval_transition.rb
  lib/catalog/order_state_transition.rb
  lib/catalog/submit_next_order_item.rb
  lib/catalog/submit_order.rb
  lib/catalog/submit_order_item.rb
  lib/kafka_listener.rb
  public/doc/openapi-3-v1.2.json
  spec/lib/catalog/approval_transition_spec.rb
  spec/lib/catalog/submit_next_order_item_spec.rb
  spec/lib/catalog/submit_order_item_spec.rb
  spec/lib/kafka_listener_spec.rb
  spec/models/order_item_spec.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/requests/api/v1.2/tags_controller_spec.rb
  spec/services/api/v1.2/catalog/evaluate_order_process_spec.rb
  spec/support/order_item_with_service_plan_helper.rb
Labels: dependencies, stable

#827 Persist artifacts in order_items table
  db/migrate/20201002135431_add_artifacts_to_order_items.rb
  db/schema.rb
  lib/catalog/determine_task_relevancy.rb
  lib/catalog/update_order_item.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
  spec/lib/catalog/update_order_item_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
Labels: sql migration

#829 Migrated ancillary metadata to previous portfolio items
  db/migrate/20201006172019_add_ancillary_metadata_to_portfolio_item.rb
  db/schema.rb
  spec/lib/kafka_listener_spec.rb
Labels: sql migration

#830 [Stable] Fixes to Sprint 62 issues
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  db/migrate/20201002135431_add_artifacts_to_order_items.rb
  db/migrate/20201006172019_add_ancillary_metadata_to_portfolio_item.rb
  db/schema.rb
  lib/catalog/approval_transition.rb
  lib/catalog/determine_task_relevancy.rb
  lib/catalog/update_order_item.rb
  spec/lib/catalog/approval_transition_spec.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
  spec/lib/catalog/update_order_item_spec.rb
  spec/lib/kafka_listener_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
  spec/models/portfolio_item_spec.rb
  spec/models/portfolio_spec.rb
  spec/requests/api/v1.1/portfolio_items_controller_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
Labels: sql migration, stable

#832 Substitute parameters before submitting order
  Gemfile
  lib/catalog/order_item_sanitized_parameters.rb
  lib/catalog/workspace_builder.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/submit_order_item_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
Labels: dependencies

#836 Sprint 63 merge master to stable
  Gemfile
  app/services/api/v1x2/catalog/evaluate_order_process.rb
  lib/catalog/order_item_sanitized_parameters.rb
  lib/catalog/workspace_builder.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/submit_order_item_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
  spec/services/api/v1.2/catalog/evaluate_order_process_spec.rb
Labels: dependencies, stable

#833 Add internal_sequence to order_processes
  app/models/order_process.rb
  db/migrate/20201012171120_add_internal_sequence_to_order_processes.rb
  db/schema.rb
  spec/models/order_process_spec.rb
Labels: sql migration

#848 Merge to Stable Sprint 64
  .codeclimate.yml
  .rubocop.yml
  app/controllers/api/v1x2/orders_controller.rb
  app/controllers/internal/v0/notify_controller.rb
  app/controllers/internal/v1x0.rb
  app/models/order_process.rb
  app/models/order_process_tag.rb
  app/models/tag.rb
  app/policies/order_process_policy.rb
  app/policies/portfolio_item_policy.rb
  app/policies/portfolio_policy.rb
  app/services/api/v1x2.rb
  app/services/api/v1x2/catalog/create_request_for_applied_inventories.rb
  app/services/api/v1x2/catalog/evaluate_order_process.rb
  config/routes.rb
  config/routes/v1x0_internal.rb
  config/routes/v1x2.rb
  db/migrate/20201012171120_add_internal_sequence_to_order_processes.rb
  db/schema.rb
  lib/approval/event_listener.rb
  lib/catalog/create_approval_request.rb
  lib/catalog/create_request_body_from.rb
  lib/catalog/determine_task_relevancy.rb
  lib/catalog/evaluate_order_process.rb
  lib/catalog/order_item_sanitized_parameters.rb
  lib/catalog/workspace_builder.rb
  lib/tags/collect_tag_resources.rb
  lib/topological_inventory/event_listener.rb
  public/doc/openapi-3-v1.2.json
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/lib/approval/event_listener_spec.rb
  spec/lib/catalog/create_approval_request_spec.rb
  spec/lib/catalog/create_request_body_from_spec.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
  spec/lib/catalog/evaluate_order_process_spec.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/submit_order_item_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
  spec/lib/tags/collect_tag_resources_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
  spec/models/order_process_spec.rb
  spec/open_api_spec.rb
  spec/policies/order_process_policy_spec.rb
  spec/policies/portfolio_item_policy_spec.rb
  spec/policies/portfolio_policy_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
  spec/requests/api/v1.1/portfolio_items_controller_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/requests/api/v1.2/orders_controller_spec.rb
  spec/requests/api/v1.2/portfolio_items_controller_spec.rb
  spec/requests/api/v1.2/tags_controller_spec.rb
  spec/spec_helper.rb
  spec/support/v1_internal_helper.rb
Labels: sql migration, stable
