Repository RedHatInsights/catalog-api, pull requests merged in 2020-01, with the labels that each got.

#532 Use topological inventory client v2.0
  spec/models/service_plan_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/service_plans_spec.rb
  spec/services/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/import_service_plans_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/provider_control_parameters_spec.rb
  spec/services/catalog/service_plans_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/update_order_item_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
Labels: bug

#534 Sprint 42 Hotfix #3 merge to stable
  Gemfile
  app/services/catalog/add_to_order.rb
  app/services/catalog/create_approval_request.rb
  app/services/catalog/create_icon.rb
  app/services/catalog/import_service_plans.rb
  app/services/tags/collect_local_order_resources.rb
  app/services/tags/topology/remote_inventory.rb
  spec/models/service_plan_spec.rb
  spec/requests/portfolio_items_spec.rb
  spec/requests/service_plans_spec.rb
  spec/services/catalog/add_to_order_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
  spec/services/catalog/create_icon_spec.rb
  spec/services/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/import_service_plans_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/provider_control_parameters_spec.rb
  spec/services/catalog/service_plans_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/update_order_item_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/services/tags/collect_local_order_resources_spec.rb
  spec/services/tags/topology/remote_inventory_spec.rb
Labels: stable

#529 The delete action was not validating resources being deleted
  app/controllers/api/v1/mixins/rbac_mixin.rb
  spec/requests/portfolios_rbac_delete_access_spec.rb
  spec/requests/portfolios_rbac_spec.rb
Labels: bug

#518 Add spec versions for request specs
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/models/service_plan_spec.rb
  spec/requests/api/v1.0/approval_request_spec.rb
  spec/requests/api/v1.0/graphql_controller_spec.rb
  spec/requests/api/v1.0/icons_spec.rb
  spec/requests/api/v1.0/order_items_spec.rb
  spec/requests/api/v1.0/orders_rbac_spec.rb
  spec/requests/api/v1.0/orders_spec.rb
  spec/requests/api/v1.0/portfolio_items_rbac_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_delete_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_read_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_update_access_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/progress_message_spec.rb
  spec/requests/api/v1.0/root_spec.rb
  spec/requests/api/v1.0/service_plans_spec.rb
  spec/requests/api/v1.0/settings_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
  spec/requests/api/v1.0/tenant_spec.rb
  spec/requests/approval_request_spec.rb
  spec/requests/root_spec.rb
  spec/services/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/import_service_plans_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/provider_control_parameters_spec.rb
  spec/services/catalog/service_plans_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/update_order_item_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/services/tags/topology/remote_inventory_spec.rb
  spec/spec_helper.rb
  spec/support/requests_spec_helper.rb
  spec/support/service_spec_helper.rb
  spec/support/v1_helper.rb
  spec/support/v1_internal_helper.rb
Labels: testing

#535 Sprint 42 merge to stable
  app/controllers/api/v1/mixins/rbac_mixin.rb
  app/controllers/api/v1/mixins/service_offering_mixin.rb
  app/controllers/api/v1/orders_controller.rb
  app/services/catalog/add_to_order.rb
  app/services/catalog/create_request_for_applied_inventories.rb
  app/services/catalog/service_offering.rb
  config/initializers/custom_exception_mappings.rb
  lib/exceptions.rb
  public/doc/openapi-3-v1.0.0.json
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/models/service_plan_spec.rb
  spec/requests/api/v1.0/approval_request_spec.rb
  spec/requests/api/v1.0/graphql_controller_spec.rb
  spec/requests/api/v1.0/icons_spec.rb
  spec/requests/api/v1.0/order_items_spec.rb
  spec/requests/api/v1.0/orders_rbac_spec.rb
  spec/requests/api/v1.0/orders_spec.rb
  spec/requests/api/v1.0/portfolio_items_rbac_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_delete_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_read_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_update_access_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/progress_message_spec.rb
  spec/requests/api/v1.0/root_spec.rb
  spec/requests/api/v1.0/service_plans_spec.rb
  spec/requests/api/v1.0/settings_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
  spec/requests/api/v1.0/tenant_spec.rb
  spec/requests/approval_request_spec.rb
  spec/requests/root_spec.rb
  spec/services/catalog/add_to_order_spec.rb
  spec/services/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/import_service_plans_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/provider_control_parameters_spec.rb
  spec/services/catalog/service_offering_spec.rb
  spec/services/catalog/service_plans_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/update_order_item_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/services/tags/topology/remote_inventory_spec.rb
  spec/spec_helper.rb
  spec/support/requests_spec_helper.rb
  spec/support/service_spec_helper.rb
  spec/support/v1_helper.rb
  spec/support/v1_internal_helper.rb
Labels: stable

#546 Sprint 43 Hotfix #1 merge to stable
  Gemfile
  README.md
  app/controllers/internal/v0/notify_controller.rb
  app/services/catalog/determine_task_relevancy.rb
  public/doc/openapi-3-v1.0.0.json
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
Labels: stable

#555 Fix icon tests to use the right form helper methods
  spec/requests/api/v1.0/icons_spec.rb
Labels: bug

#554 Raise ActiveRecord::RecordNotFound if /service_plans/:id/{base,modified} not found
  app/services/catalog/service_plan_json.rb
  spec/requests/api/v1.0/service_plans_spec.rb
Labels: bug

#553 Add a regex to validate tag values
  public/doc/openapi-3-v1.0.0.json
  spec/open_api_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/support/random_words_spec_helper.rb
Labels: bug

#549 Added approval_url sources_url spec helpers
  spec/lib/approval/service_spec.rb
  spec/lib/catalog/survey_compare_spec.rb
  spec/lib/sources_spec.rb
  spec/models/service_plan_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/services/catalog/cancel_order_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
  spec/services/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/catalog/service_offering_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/update_order_item_spec.rb
  spec/services/catalog/validate_source_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/services/tags/topology/remote_inventory_spec.rb
  spec/support/service_spec_helper.rb
  spec/support/topology_spec_helper.rb
Labels: refactoring, testing

#552 Add the approval request external reference to progress message
  app/models/approval_request.rb
  app/services/catalog/create_approval_request.rb
  spec/models/approval_request_spec.rb
Labels: bug

#561 Normalize rbac ace table and added readonly permissions table
  app/controllers/api/v1/mixins/ace_mixin.rb
  app/models/access_control_entry.rb
  app/models/access_control_permission.rb
  app/models/permission.rb
  app/services/catalog/share_info.rb
  app/services/catalog/share_resource.rb
  app/services/catalog/unshare_resource.rb
  db/migrate/20200114164456_normalize_ace_table.rb
  db/schema.rb
  spec/factories/access_control_entry.rb
  spec/factories/access_control_permission.rb
  spec/factories/permission.rb
  spec/models/access_control_entry_spec.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_delete_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_read_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_update_access_spec.rb
  spec/services/catalog/share_info_spec.rb
  spec/services/catalog/share_resource_spec.rb
  spec/services/catalog/unshare_resource_spec.rb
  spec/support/sharing_objects.rb
Labels: refactoring

#573 Use Pundit for portfolio_item collection scoping on portfolios
  Gemfile
  app/controllers/api/v1/portfolio_items_controller.rb
  app/controllers/application_controller.rb
  app/policies/application_policy.rb
  app/policies/portfolio_item_policy.rb
  config/initializers/custom_exception_mappings.rb
  spec/policies/portfolio_item_policy_scope_spec.rb
  spec/requests/api/v1.0/portfolio_items_rbac_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
Labels: unmergeable
