Repository RedHatInsights/catalog-api, pull requests merged in 2020-04, with the labels that each got.

#654 [Stable] Fix incorrect policy being used for PortfolioItemsController#create
  app/controllers/api/v1x0/portfolio_items_controller.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
Labels: stable

#657 [Stable] Store UserContext object on the current thread to reduce RBAC calls
  app/controllers/application_controller.rb
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  app/services/catalog/user_capabilities.rb
Labels: stable

#661 Fixes order of items in spec comparison
  spec/policies/portfolio_item_policy_scope_spec.rb
Labels: testing

#674 Sprint 50 merge to stable
  app/controllers/application_controller.rb
  app/models/concerns/user_capabilities.rb
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  app/policies/user_context.rb
  app/services/catalog/unshare_resource.rb
  app/services/catalog/user_capabilities.rb
  public/doc/openapi-3-v1.0.json
  public/doc/openapi-3-v1.1.json
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/controllers/internal/v1x0/notify_controller_spec.rb
  spec/policies/order_policy_scope_spec.rb
  spec/policies/portfolio_item_policy_scope_spec.rb
  spec/policies/user_context_spec.rb
  spec/requests/api/v1.0/approval_request_spec.rb
  spec/requests/api/v1.0/graphql_controller_rbac_spec.rb
  spec/requests/api/v1.0/graphql_controller_spec.rb
  spec/requests/api/v1.0/order_items_spec.rb
  spec/requests/api/v1.0/orders_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/progress_message_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/requests/api/v1/application_controller_spec.rb
  spec/services/catalog/unshare_resource_spec.rb
  spec/support/requests_spec_helper.rb
Labels: stable

#685 [Stable] Fix access scope call to use proper object table name
  lib/catalog/rbac/access.rb
  spec/factories/access_control_entry.rb
  spec/factories/access_control_permission.rb
  spec/lib/catalog/rbac/access_spec.rb
Labels: stable

#687 [Stable] Ensure only users in the portfolio update admin scope can share/unshare
  app/policies/portfolio_policy.rb
  lib/catalog/rbac/access.rb
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/lib/catalog/rbac/access_spec.rb
  spec/policies/portfolio_policy_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/requests/api/v1/application_controller_spec.rb
Labels: stable

#691 [Stable] Return an empty array when groups have no permissions
  app/services/catalog/share_info.rb
  spec/services/catalog/share_info_spec.rb
Labels: stable

#680 Change the `external_url` setting to handle topo changes
  app/services/catalog/determine_task_relevancy.rb
  app/services/catalog/update_order_item.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/update_order_item_spec.rb
Labels: enhancement

#679 Move group_names RBAC call to UserContext
  app/controllers/api/v1x0/portfolios_controller.rb
  app/policies/user_context.rb
  app/services/catalog/share_info.rb
  spec/policies/user_context_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/services/catalog/share_info_spec.rb
Labels: refactoring

#706 Renamed a method to reflect the data it stores
  app/services/group/seed.rb
Labels: refactoring

#713 Sprint 51 merge to stable
  Gemfile
  app/controllers/api/v1x0/graphql_controller.rb
  app/controllers/api/v1x0/mixins/ace_mixin.rb
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/tags_controller.rb
  app/controllers/application_controller.rb
  app/models/concerns/user_capabilities.rb
  app/models/portfolio.rb
  app/policies/application_policy.rb
  app/policies/portfolio_item_policy.rb
  app/policies/portfolio_policy.rb
  app/policies/user_context.rb
  app/services/catalog/copy_portfolio_item.rb
  app/services/catalog/determine_task_relevancy.rb
  app/services/catalog/order_item_sanitized_parameters.rb
  app/services/catalog/share_info.rb
  app/services/catalog/update_order_item.rb
  app/services/group/seed.rb
  config/initializers/action_dispatch-routing-option_redirect.rb
  lib/catalog/rbac/access.rb
  lib/catalog/rbac/access_control_entries.rb
  public/doc/openapi-3-v1.0.json
  public/doc/openapi-3-v1.1.json
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/lib/catalog/rbac/access_control_entries_spec.rb
  spec/lib/catalog/rbac/access_spec.rb
  spec/models/portfolio_item_spec.rb
  spec/models/portfolio_spec.rb
  spec/policies/application_policy_spec.rb
  spec/policies/portfolio_item_policy_spec.rb
  spec/policies/portfolio_policy_spec.rb
  spec/policies/user_context_spec.rb
  spec/requests/api/v1.0/portfolio_items_rbac_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/root_spec.rb
  spec/requests/api/v1.0/tenant_spec.rb
  spec/requests/api/v1.1/portfolio_items_controller_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/services/catalog/add_to_order_spec.rb
  spec/services/catalog/copy_portfolio_item_spec.rb
  spec/services/catalog/create_approval_request_spec.rb
  spec/services/catalog/create_icon_spec.rb
  spec/services/catalog/create_request_body_from_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/service_plan_reset_spec.rb
  spec/services/catalog/share_info_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/services/catalog/update_order_item_spec.rb
  spec/support/images/no_header_miq_logo.svg
  spec/support/service_offering_topological_service_offering_helper.rb
  spec/support/service_spec_helper.rb
  spec/support/sharing_objects.rb
Labels: stable
