Repository RedHatInsights/catalog-api, pull requests merged in 2020-02, with the labels that each got.

#577 Sprint 45 merge to stable
  Gemfile
  README.md
  app/controllers/api/v1/mixins/ace_mixin.rb
  app/controllers/api/v1/portfolio_items_controller.rb
  app/controllers/api/v1/portfolios_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/controllers/application_controller.rb
  app/controllers/status_controller.rb
  app/models/access_control_entry.rb
  app/models/access_control_permission.rb
  app/models/image.rb
  app/models/permission.rb
  app/models/portfolio_item.rb
  app/policies/application_policy.rb
  app/policies/portfolio_item_policy.rb
  app/services/catalog/determine_task_relevancy.rb
  app/services/catalog/share_info.rb
  app/services/catalog/share_resource.rb
  app/services/catalog/unshare_resource.rb
  config/initializers/custom_exception_mappings.rb
  config/routes.rb
  db/migrate/20200114164456_normalize_ace_table.rb
  db/schema.rb
  public/doc/openapi-3-v1.0.0.json
  spec/factories/access_control_entry.rb
  spec/factories/access_control_permission.rb
  spec/factories/permission.rb
  spec/models/access_control_entry_spec.rb
  spec/open_api_spec.rb
  spec/policies/portfolio_item_policy_scope_spec.rb
  spec/requests/api/v1.0/icons_spec.rb
  spec/requests/api/v1.0/portfolio_items_rbac_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_delete_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_read_access_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_spec.rb
  spec/requests/api/v1.0/portfolios_rbac_update_access_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
  spec/services/catalog/determine_task_relevancy_spec.rb
  spec/services/catalog/share_info_spec.rb
  spec/services/catalog/share_resource_spec.rb
  spec/services/catalog/unshare_resource_spec.rb
  spec/support/sharing_objects.rb
Labels: stable

#588 Allow for force reimporting of service_plans on reset
  app/services/catalog/import_service_plans.rb
  app/services/catalog/service_plan_reset.rb
  spec/lib/catalog/rbac/access_control_entries_spec.rb
  spec/services/catalog/import_service_plans_spec.rb
  spec/services/catalog/service_plan_reset_spec.rb
Labels: bug

#582 Create a pattern for handling minor api versions
  app/controllers/api/v1x1.rb
  app/controllers/api/v1x1/icons_controller.rb
  config/initializers/routing_draw.rb
  config/routes.rb
  config/routes/public.rb
  config/routes/v1x0.rb
  config/routes/v1x0_internal.rb
  config/routes/v1x1.rb
  public/doc/openapi-3-v1.0.json
  public/doc/openapi-3-v1.1.json
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.1/icons_spec.rb
  spec/requests/api/v1/application_controller_spec.rb
  spec/requests/api/v1/root_spec.rb
  spec/spec_helper.rb
  spec/support/v1x1_helper.rb
Labels: enhancement

#597 Sprint 46 Hotfix #1 merge to stable
  app/controllers/api/v1/mixins/validation_mixin.rb
  app/controllers/api/v1/portfolio_items_controller.rb
  app/controllers/api/v1/portfolios_controller.rb
  app/controllers/api/v1x1.rb
  app/controllers/api/v1x1/icons_controller.rb
  app/controllers/application_controller.rb
  app/models/order_item.rb
  app/services/catalog/create_request_body_from.rb
  app/services/catalog/order_item_sanitized_parameters.rb
  config/initializers/routing_draw.rb
  config/routes.rb
  config/routes/public.rb
  config/routes/v1x0.rb
  config/routes/v1x0_internal.rb
  config/routes/v1x1.rb
  db/migrate/20200212122000_add_service_parameters_raw.rb
  db/schema.rb
  public/doc/openapi-3-v1.0.json
  public/doc/openapi-3-v1.1.json
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/factories/order_item.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.1/icons_spec.rb
  spec/requests/api/v1/application_controller_spec.rb
  spec/requests/api/v1/root_spec.rb
  spec/services/catalog/create_request_body_from_spec.rb
  spec/services/catalog/order_item_sanitized_parameters_spec.rb
  spec/services/catalog/submit_order_spec.rb
  spec/spec_helper.rb
  spec/support/order_item_with_service_plan_helper.rb
  spec/support/v1x1_helper.rb
Labels: stable

#601 [Stable] Use the rubygems version of the topo ruby client gem
  Gemfile
Labels: stable

#607 Send platform information to Approval
  app/services/catalog/create_request_body_from.rb
  spec/lib/sources_spec.rb
  spec/services/catalog/create_request_body_from_spec.rb
  spec/services/catalog/validate_source_spec.rb
  spec/services/service_offering/add_to_portfolio_item_spec.rb
  spec/spec_helper.rb
  spec/support/service_spec_helper.rb
  spec/support/sources_spec_helper.rb
Labels: enhancement
