Repository RedHatInsights/catalog-api, pull requests merged in 2020-09, with the labels that each got.

#812 Do not raise an error if task_id does not belong to any order_item
  lib/catalog/determine_task_relevancy.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
Labels: bug

#814 Sprint 61 merge master to stable
  app/controllers/api/v1x1/icons_controller.rb
  app/controllers/api/v1x1/portfolio_items_controller.rb
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/icons_controller.rb
  app/controllers/api/v1x2/portfolio_items_controller.rb
  app/services/api/v1x0/catalog/create_request_for_applied_inventories.rb
  lib/catalog/create_approval_request.rb
  lib/catalog/determine_task_relevancy.rb
  lib/catalog/submit_order.rb
  lib/catalog/update_order_item.rb
  lib/kafka_listener.rb
  spec/lib/approval/event_listener_spec.rb
  spec/lib/catalog/create_approval_request_spec.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
  spec/lib/catalog/submit_order_spec.rb
  spec/lib/catalog/update_order_item_spec.rb
  spec/lib/kafka_listener_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
  spec/models/order_item_spec.rb
  spec/requests/api/v1.2/icons_spec.rb
  spec/requests/api/v1.2/portfolio_items_controller_spec.rb
  spec/services/api/v1.0/catalog/create_request_for_applied_inventories_spec.rb
Labels: stable

#815 Switch to rdkafka gem
  Dockerfile
  Gemfile
  docker-assets/librdkafka-1.5.0.tar.gz
  lib/kafka_listener.rb
  spec/lib/kafka_listener_spec.rb
Labels: dependencies

#817 Pin puma to not upgrade to 5.0
  Gemfile
Labels: dependencies

#824 Update manageiq-messaging to 1.0
  Gemfile
  lib/kafka_listener.rb
  spec/lib/kafka_listener_spec.rb
Labels: dependencies
