Repository RedHatInsights/catalog-api, pull requests merged in 2020-06, with the labels that each got.

#760 Sprint 54 merge to stable
  .travis_scripts/openapi-validator.sh
  Gemfile
  Jenkinsfile-smoke.groovy
  app/controllers/api/v1x0.rb
  app/controllers/api/v1x0/mixins/rbac_mixin.rb
  app/controllers/api/v1x0/settings_controller.rb
  app/controllers/api/v1x0/tenants_controller.rb
  app/controllers/api/v1x1.rb
  app/controllers/api/v1x1/icons_controller.rb
  app/controllers/api/v1x1/service_plans_controller.rb
  app/models/ancillary_metadata.rb
  app/models/concerns/metadata/ancillary.rb
  app/models/portfolio.rb
  app/models/portfolio_item.rb
  app/policies/tenant_policy.rb
  app/services/api/v1x0.rb
  app/services/api/v1x0/catalog/copy_portfolio_item.rb
  app/services/api/v1x0/catalog/share_resource.rb
  app/services/api/v1x0/catalog/unshare_resource.rb
  app/services/api/v1x1.rb
  app/services/api/v1x1/catalog/service_plan_reset.rb
  db/migrate/20200424122000_add_ancillary_metadata_to_portfolio.rb
  db/schema.rb
  lib/catalog/data_driven_form_validator.rb
  public/doc/openapi-3-v1.0.json
  public/doc/openapi-3-v1.1.json
  spec/controllers/api/v1x0/application_controller_spec.rb
  spec/factories/access_control_entry.rb
  spec/lib/catalog/data_driven_form_validator_spec.rb
  spec/models/ancillary_metadata_spec.rb
  spec/models/portfolio_item_spec.rb
  spec/models/portfolio_spec.rb
  spec/open_api_spec.rb
  spec/policies/tenant_policy_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.0/settings_spec.rb
  spec/requests/api/v1.0/tenant_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/requests/api/v1.1/service_plans_controller_spec.rb
  spec/requests/status_spec.rb
  spec/services/api/v1.0/catalog/share_resource_spec.rb
  spec/services/api/v1.0/catalog/unshare_resource_spec.rb
  spec/services/api/v1.0/service_offering/add_to_portfolio_item_spec.rb
  spec/services/api/v1.1/catalog/service_plan_reset_spec.rb
  spec/support/ddf/valid_service_plan_ddf_v2.json
  spec/support/requests_spec_helper.rb
Labels: dependencies, sql migration, stable

#761 Create OrderProcess model
  app/models/order_process.rb
  app/models/order_process_tag.rb
  app/models/tag.rb
  db/migrate/20200610185514_add_order_process.rb
  db/schema.rb
  spec/factories/order_process.rb
  spec/models/order_process_spec.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
Labels: ITSM, sql migration

#764 Expose OrderProcess CRUD APIs
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/order_processes_controller.rb
  config/routes.rb
  config/routes/v1x2.rb
  public/doc/openapi-3-v1.2.json
  spec/open_api_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/requests/api/v1/application_controller_spec.rb
  spec/requests/api/v1/root_spec.rb
  spec/spec_helper.rb
  spec/support/v1x2_helper.rb
Labels: ITSM

#766 Sprint 55 merge to stable
  app/controllers/api/v1x1.rb
  app/controllers/api/v1x1/portfolio_items_controller.rb
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/order_processes_controller.rb
  app/models/order_process.rb
  app/models/order_process_tag.rb
  app/models/tag.rb
  app/policies/order_process_policy.rb
  config/routes.rb
  config/routes/v1x2.rb
  db/migrate/20200610185514_add_order_process.rb
  db/schema.rb
  lib/task_helpers/metrics.rb
  lib/tasks/metrics.rake
  public/doc/openapi-3-v1.2.json
  spec/factories/order_process.rb
  spec/lib/tasks/metrics_spec.rb
  spec/lib/tasks_helpers/metrics_spec.rb
  spec/models/order_process_spec.rb
  spec/open_api_spec.rb
  spec/policies/order_process_policy_scope_spec.rb
  spec/policies/order_process_policy_spec.rb
  spec/requests/api/v1.0/tags_spec.rb
  spec/requests/api/v1.1/portfolio_items_controller_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/requests/api/v1/application_controller_spec.rb
  spec/requests/api/v1/root_spec.rb
  spec/spec_helper.rb
  spec/support/v1x2_helper.rb
Labels: sql migration, stable
