Repository RedHatInsights/catalog-api, pull requests merged in 2020-03, with the labels that each got.

#624 [Stable] Code Cleanup
  lib/catalog/rbac/access.rb
Labels: stable

#640 Add after_discard callback on Icon to handle nullifying restore_to reference
  app/models/icon.rb
  spec/requests/api/v1.1/icons_spec.rb
Labels: bug

#642 Remove v1 namespace
  app/controllers/api/v1.rb
  app/controllers/api/v1x0.rb
  app/controllers/api/v1x0/approval_requests_controller.rb
  app/controllers/api/v1x0/graphql_controller.rb
  app/controllers/api/v1x0/icons_controller.rb
  app/controllers/api/v1x0/mixins/ace_mixin.rb
  app/controllers/api/v1x0/mixins/index_mixin.rb
  app/controllers/api/v1x0/mixins/rbac_mixin.rb
  app/controllers/api/v1x0/mixins/service_offering_mixin.rb
  app/controllers/api/v1x0/mixins/show_mixin.rb
  app/controllers/api/v1x0/mixins/validation_mixin.rb
  app/controllers/api/v1x0/order_items_controller.rb
  app/controllers/api/v1x0/orders_controller.rb
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/progress_messages_controller.rb
  app/controllers/api/v1x0/provider_control_parameters_controller.rb
  app/controllers/api/v1x0/service_plans_controller.rb
  app/controllers/api/v1x0/settings_controller.rb
  app/controllers/api/v1x0/tags_controller.rb
  app/controllers/api/v1x0/tenants_controller.rb
  app/controllers/api/v1x1.rb
  app/controllers/api/v1x1/icons_controller.rb
  app/controllers/application_controller.rb
  app/policies/application_policy.rb
Labels: refactoring
