Repository RedHatInsights/catalog-api, pull requests merged in 2020-08, with the labels that each got.

#789 Sprint 58 merge to stable
  .travis.yml
  Dockerfile
  app/controllers/api/v1x2/mixins/index_mixin.rb
  app/controllers/api/v1x2/order_processes_controller.rb
  app/policies/order_process_policy.rb
  app/services/api/v1x0/catalog/copy_portfolio.rb
  app/services/api/v1x2/catalog/get_linked_order_process.rb
  app/services/api/v1x2/catalog/link_to_order_process.rb
  app/services/api/v1x2/catalog/tagging_service.rb
  app/services/api/v1x2/catalog/unlink_from_order_process.rb
  config/routes/v1x2.rb
  lib/catalog/rbac/access.rb
  public/doc/openapi-3-v1.2.json
  spec/policies/order_process_policy_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/services/api/v1.0/catalog/copy_portfolio_spec.rb
  spec/services/api/v1.2/catalog/get_linked_order_process_spec.rb
  spec/services/api/v1.2/catalog/link_to_order_process_spec.rb
  spec/services/api/v1.2/catalog/unlink_from_order_process_spec.rb
  spec/support/order_process_tag_links_helper.rb
Labels: stable

#785 Add process_sequence and process_scope columns for order_items
  db/migrate/20200731045804_add_order_item_process_columns.rb
  db/schema.rb
  public/doc/openapi-3-v1.2.json
Labels: sql migration

#792 Add topolical_inventory event listener
  Gemfile
  app/services/api/v1x0/catalog/create_request_for_applied_inventories.rb
  app/services/api/v1x0/catalog/order_item_sanitized_parameters.rb
  app/services/api/v1x0/catalog/provider_control_parameters.rb
  app/services/api/v1x0/catalog/service_offering.rb
  app/services/api/v1x0/catalog/service_plans.rb
  app/services/api/v1x0/catalog/submit_order.rb
  app/services/api/v1x0/service_offering/add_to_portfolio_item.rb
  app/services/api/v1x0/tags/topology/remote_inventory.rb
  app/services/api/v1x1/catalog/portfolio_item_orderable.rb
  app/services/api/v1x2/catalog/tagging_service.rb
  config/initializers/approval_listener.rb
  config/initializers/load_extensions.rb
  config/initializers/topological_inventory_listener.rb
  lib/approval/event_listener.rb
  lib/catalog/survey_compare.rb
  lib/kafka_listener.rb
  lib/topological_inventory.rb
  lib/topological_inventory/event_listener.rb
  lib/topological_inventory/service.rb
  spec/lib/approval/event_listener_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
  spec/lib/topological_inventory/service_spec.rb
Labels: dependencies

#795 Sprint 59 merge to stable
  Gemfile
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/tags_controller.rb
  app/policies/order_process_policy.rb
  app/policies/portfolio_item_policy.rb
  app/policies/portfolio_policy.rb
  app/services/api/v1x0/catalog/create_request_for_applied_inventories.rb
  app/services/api/v1x0/catalog/order_item_sanitized_parameters.rb
  app/services/api/v1x0/catalog/provider_control_parameters.rb
  app/services/api/v1x0/catalog/service_offering.rb
  app/services/api/v1x0/catalog/service_plans.rb
  app/services/api/v1x0/catalog/submit_order.rb
  app/services/api/v1x0/service_offering/add_to_portfolio_item.rb
  app/services/api/v1x0/tags/topology/remote_inventory.rb
  app/services/api/v1x1/catalog/portfolio_item_orderable.rb
  app/services/api/v1x2/catalog/tagging_service.rb
  app/services/concerns/tagging_mixin.rb
  config/initializers/approval_listener.rb
  config/initializers/load_extensions.rb
  config/initializers/topological_inventory_listener.rb
  config/routes/v1x0.rb
  config/routes/v1x1.rb
  config/routes/v1x2.rb
  db/migrate/20200731045804_add_order_item_process_columns.rb
  db/schema.rb
  lib/approval/event_listener.rb
  lib/catalog/survey_compare.rb
  lib/kafka_listener.rb
  lib/topological_inventory.rb
  lib/topological_inventory/event_listener.rb
  lib/topological_inventory/service.rb
  public/doc/openapi-3-v1.2.json
  spec/lib/approval/event_listener_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
  spec/lib/topological_inventory/service_spec.rb
  spec/policies/order_process_policy_spec.rb
  spec/policies/portfolio_item_policy_spec.rb
  spec/policies/portfolio_policy_spec.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.1/portfolio_items_controller_spec.rb
  spec/requests/api/v1.1/portfolios_controller_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/support/authorize_shared_examples.rb
  spec/support/tagging_shared_examples.rb
Labels: dependencies, sql migration, stable

#797 Make sure task_id is string type
  lib/catalog/determine_task_relevancy.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
Labels: bug

#786 Evaluate order process during OrderController#submit_order
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/orders_controller.rb
  app/services/api/v1x2.rb
  app/services/api/v1x2/catalog/add_to_order_via_order_process.rb
  app/services/api/v1x2/catalog/create_request_for_applied_inventories.rb
  app/services/api/v1x2/catalog/evaluate_order_process.rb
  lib/catalog/create_approval_request.rb
  lib/catalog/submit_order.rb
  spec/factories/order_process.rb
  spec/lib/catalog/create_approval_request_spec.rb
  spec/lib/catalog/submit_order_spec.rb
  spec/requests/api/v1.2/orders_controller_spec.rb
  spec/services/api/v1.2/catalog/add_to_order_via_order_process_spec.rb
  spec/services/api/v1.2/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/api/v1.2/catalog/evaluate_order_process_spec.rb
  spec/support/order_item_with_service_plan_helper.rb
Labels: sql migration
