Repository RedHatInsights/catalog-api, pull requests merged in 2020-11, with the labels that each got.

#854 [Stable] Sprint 64 fixes; merge master to stable
  app/controllers/api/v1x0/mixins/service_offering_mixin.rb
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/orders_controller.rb
  app/services/api/v1x0/catalog/create_request_for_applied_inventories.rb
  lib/catalog/evaluate_order_process.rb
  lib/catalog/order_item_sanitized_parameters.rb
  lib/catalog/service_plan_fields.rb
  spec/lib/catalog/evaluate_order_process_spec.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/service_plan_fields_spec.rb
  spec/requests/api/v1.0/orders_spec.rb
  spec/requests/api/v1.2/orders_controller_spec.rb
Labels: stable

#856 Replace applicable with product in workspace and substitution
  lib/catalog/order_item_sanitized_parameters.rb
  lib/catalog/workspace_builder.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
Labels: unmergeable

#857 [Stable] Sprint 64 fixes round 2; merge master to stable
  lib/catalog/determine_task_relevancy.rb
  lib/catalog/order_item_sanitized_parameters.rb
  lib/catalog/update_order_item.rb
  lib/catalog/workspace_builder.rb
  spec/lib/catalog/determine_task_relevancy_spec.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/update_order_item_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
  spec/lib/topological_inventory/event_listener_spec.rb
Labels: stable

#858 Set internal sequence from nil value
  db/migrate/20201104115520_set_internal_sequence_value.rb
Labels: sql migration

#861 [Stable] Sprint 64 fixes round 3; merge master to stable
  db/migrate/20201104115520_set_internal_sequence_value.rb
  lib/catalog/update_order_item.rb
  spec/lib/catalog/update_order_item_spec.rb
Labels: sql migration, stable

#862 Add name to order_item
  app/services/api/v1x0/catalog/add_to_order.rb
  db/migrate/20201105135352_add_name_to_order_items.rb
  db/schema.rb
  lib/catalog/evaluate_order_process.rb
  lib/catalog/workspace_builder.rb
  public/doc/openapi-3-v1.2.json
  spec/lib/catalog/evaluate_order_process_spec.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
  spec/services/api/v1.0/catalog/add_to_order_spec.rb
Labels: sql migration

#864 Sprint 66 merge master to stable
  app/models/service_plan.rb
  app/services/api/v1x0/catalog/add_to_order.rb
  app/services/api/v1x0/catalog/create_request_for_applied_inventories.rb
  app/services/api/v1x0/catalog/service_plan_compare.rb
  db/migrate/20201105135352_add_name_to_order_items.rb
  db/schema.rb
  lib/catalog/evaluate_order_process.rb
  lib/catalog/submit_order_item.rb
  lib/catalog/survey_compare.rb
  lib/catalog/workspace_builder.rb
  public/doc/openapi-3-v1.2.json
  spec/lib/catalog/evaluate_order_process_spec.rb
  spec/lib/catalog/order_item_sanitized_parameters_spec.rb
  spec/lib/catalog/submit_order_item_spec.rb
  spec/lib/catalog/survey_compare_spec.rb
  spec/lib/catalog/workspace_builder_spec.rb
  spec/models/service_plan_spec.rb
  spec/requests/api/v1.0/orders_spec.rb
  spec/services/api/v1.0/catalog/add_to_order_spec.rb
  spec/services/api/v1.0/catalog/create_request_for_applied_inventories_spec.rb
  spec/services/api/v1.0/catalog/service_plan_compare_spec.rb
  spec/services/api/v1.2/catalog/create_request_for_applied_inventories_spec.rb
Labels: sql migration, stable
