Repository RedHatInsights/catalog-api, pull requests merged in 2020-07, with the labels that each got.

#773 Sprint 56 merge to stable
  .travis.yml
  .travis_scripts/openapi-validator.sh
  app/controllers/api/v1x0/approval_requests_controller.rb
  app/controllers/api/v1x0/graphql_controller.rb
  app/controllers/api/v1x0/icons_controller.rb
  app/controllers/api/v1x0/order_items_controller.rb
  app/controllers/api/v1x0/orders_controller.rb
  app/controllers/api/v1x0/portfolio_items_controller.rb
  app/controllers/api/v1x0/portfolios_controller.rb
  app/controllers/api/v1x0/progress_messages_controller.rb
  app/controllers/api/v1x0/service_plans_controller.rb
  app/controllers/api/v1x0/tags_controller.rb
  app/controllers/api/v1x0/tenants_controller.rb
  app/controllers/api/v1x1.rb
  app/controllers/api/v1x1/icons_controller.rb
  app/controllers/api/v1x1/mixins/index_mixin.rb
  app/controllers/api/v1x1/mixins/show_mixin.rb
  app/controllers/api/v1x1/service_plans_controller.rb
  app/controllers/api/v1x2.rb
  app/controllers/api/v1x2/mixins/index_mixin.rb
  app/controllers/api/v1x2/mixins/show_mixin.rb
  app/controllers/api/v1x2/order_processes_controller.rb
  app/services/api/v1x2.rb
  spec/requests/api/v1.0/portfolio_items_spec.rb
  spec/requests/api/v1.0/portfolios_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/support/tagging_shared_examples.rb
Labels: stable

#771 Add 'before' API endpoint for order processes
  app/controllers/api/v1x2/order_processes_controller.rb
  app/models/order_process.rb
  app/services/api/v1x2/catalog/order_process_associator.rb
  config/routes/v1x2.rb
  db/migrate/20200626043755_add_before_portfolio_item_id_to_order_processes.rb
  db/schema.rb
  public/doc/openapi-3-v1.2.json
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/services/api/v1.2/order_process_associator_spec.rb
Labels: sql migration

#777 Add tag link table
  app/models/order_process.rb
  app/models/tag_link.rb
  db/migrate/20200709201525_create_tag_links.rb
  db/schema.rb
  spec/factories/tag_links.rb
  spec/models/order_process_spec.rb
  spec/models/tag_link_spec.rb
  spec/open_api_spec.rb
Labels: sql migration

#772 Add 'after' API endpoint for order processes
  app/controllers/api/v1x2/order_processes_controller.rb
  app/models/order_process.rb
  config/routes/v1x2.rb
  db/migrate/20200707095138_add_after_portfolio_item_id_to_order_processes.rb
  db/schema.rb
  public/doc/openapi-3-v1.2.json
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/services/api/v1.2/order_process_associator_spec.rb
Labels: sql migration, unmergeable

#778 Order modal text update
  spec/support/ddf/no_service_plan_ddf.json
Labels: enhancement

#781 Sprint 57 merge to stable
  app/controllers/api/v1x2/order_processes_controller.rb
  app/models/order_process.rb
  app/models/tag_link.rb
  app/services/api/v1x2/catalog/order_process_associator.rb
  app/services/api/v1x2/catalog/order_process_dissociator.rb
  config/routes/v1x2.rb
  db/migrate/20200626043755_add_before_portfolio_item_id_to_order_processes.rb
  db/migrate/20200707095138_add_after_portfolio_item_id_to_order_processes.rb
  db/migrate/20200709201525_create_tag_links.rb
  db/schema.rb
  public/doc/openapi-3-v1.2.json
  spec/factories/tag_links.rb
  spec/models/order_process_spec.rb
  spec/models/tag_link_spec.rb
  spec/open_api_spec.rb
  spec/requests/api/v1.1/root_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/requests/api/v1.2/root_spec.rb
  spec/services/api/v1.2/order_process_associator_spec.rb
  spec/services/api/v1.2/order_process_dissociator_spec.rb
  spec/support/ddf/no_service_plan_ddf.json
Labels: sql migration, stable

#779 Enable link/unlink/resolve logics on order process
  app/controllers/api/v1x2/mixins/index_mixin.rb
  app/controllers/api/v1x2/order_processes_controller.rb
  app/policies/order_process_policy.rb
  app/services/api/v1x2/catalog/get_linked_order_process.rb
  app/services/api/v1x2/catalog/link_to_order_process.rb
  app/services/api/v1x2/catalog/tagging_service.rb
  app/services/api/v1x2/catalog/unlink_from_order_process.rb
  config/routes/v1x2.rb
  lib/catalog/rbac/access.rb
  public/doc/openapi-3-v1.2.json
  spec/policies/order_process_policy_spec.rb
  spec/requests/api/v1.2/order_processes_controller_spec.rb
  spec/services/api/v1.2/catalog/get_linked_order_process_spec.rb
  spec/services/api/v1.2/catalog/link_to_order_process_spec.rb
  spec/services/api/v1.2/catalog/unlink_from_order_process_spec.rb
  spec/support/order_process_tag_links_helper.rb
Labels: dependencies
